apiVersion: apps/v1
kind: Deployment
metadata:
  name: shield
  namespace: shield
  labels:
    app: shield
spec:
  selector:
    matchLabels:
      app: shield
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shield
    spec:
      containers:
        - name: shield
          image: shield
          imagePullPolicy: Never
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: shield-k8s-environment
                  key: shield.enviroment
            - name: FLASK_KEY
              valueFrom:
                secretKeyRef:
                  name: shield-k8s-secrets
                  key: shield.password
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /shield/healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 5000
