apiVersion: v1
kind: Service
metadata:
  name: shield
  namespace: shield
  labels:
    app: shield
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: shield
  selector:
    app: shield
  type: LoadBalancer